### PR TITLE
Initial support for Cherokee as a demonstration implementation for a tone and cadence language

### PR DESCRIPTION
**Pull request by michael-conrad**
Initial support for Cherokee as a demonstration implementation for a tone and cadence language

### CODE REVIEW

**Comment by michael-conrad** [comment]
I'm getting a ```RuntimeError: CUDA error: device-side assert triggered``` that I can't figure out.

```python
python run_training_pipeline.py --gpu_id 0 --finetune --resume_checkpoint Models/FastSpeech2_Meta/best.pt chr
...
Preparing
Prepared a FastSpeech dataset with 1352 datapoints in Corpora/chr-w.
Training model
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 135/135 [00:18<00:00,  7.42it/s]
Traceback (most recent call last):
  File "run_training_pipeline.py", line 78, in <module>
    pipeline_dict[args.pipeline](gpu_id=args.gpu_id,
  File "/home/muksihs/git/IMS-Toucan/TrainingInterfaces/TrainingPipelines/FastSpeech2_Cherokee_West.py", line 45, in run
    train_loop(net=model,
  File "/home/muksihs/git/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/fastspeech2_train_loop.py", line 195, in train_loop
    plot_progress_spec(net, device, save_dir=save_directory, step=step_counter, lang=lang, default_emb=default_embedding)
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/muksihs/git/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/fastspeech2_train_loop.py", line 48, in plot_progress_spec
    spec, durations, *_ = net.inference(text=phoneme_vector,
  File "/home/muksihs/git/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/FastSpeech2.py", line 350, in inference
    before_outs, after_outs, d_outs, pitch_predictions, energy_predictions = self._forward(xs,
File "/home/muksihs/git/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/FastSpeech2.py", line 241, in _forward
    encoded_texts, _ = self.encoder(text_tensors, text_masks, utterance_embedding=utterance_embedding, lang_ids=lang_ids)  # (B, Tmax, adim)
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/muksihs/git/IMS-Toucan/Layers/Conformer.py", line 123, in forward
    xs, masks = self.encoders(xs, masks)
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/muksihs/git/IMS-Toucan/Layers/MultiSequential.py", line 18, in forward
    args = m(*args)
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/muksihs/git/IMS-Toucan/Layers/EncoderLayer.py", line 123, in forward
    x = residual + self.dropout(self.conv_module(x))
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/muksihs/git/IMS-Toucan/Layers/Convolution.py", line 51, in forward
    x = self.activation(self.norm(x))  
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 268, in forward
    return F.group_norm(
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/nn/functional.py", line 2360, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/Indexing.cu:646: indexSelectSmallIndex: block: [1,0,0], thread: [64,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/Indexing.cu:646: indexSelectSmallIndex: block: [1,0,0], thread: [65,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/Indexing.cu:646: indexSelectSmallIndex: block: [1,0,0], thread: [66,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
...
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/Indexing.cu:646: indexSelectSmallIndex: block: [0,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/Indexing.cu:646: indexSelectSmallIndex: block: [0,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/Indexing.cu:646: indexSelectSmallIndex: block: [0,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/cuda/Indexing.cu:646: indexSelectSmallIndex: block: [0,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

```

**Comment by Flux9665** [comment]
I'm not sure why it works at all and only crashes so late, you are using 511863580771 as the language ID for cherokee west and 434554169443 for cherokee east, but the language IDs only go up to 100. When you add a new language, the language ID should increase by 1 up to the maximum that you specify when you instantiate the model. For the provided multilingual checkpoint that was pretty randomly chosen to be 100.

**Comment by Flux9665** [comment]
There are several problems: 

1. You add the tone and length characters to the inventory of the aligner, which will cause the aligner to fail. They should only be visible to the TTS, not to the aligner.
2. You use utf8 encodings of strings as the language IDs, which is not viable as the input to an embedding layer, since there need to be as many placeholder tensors as there are IDs.
3. You treat all tone and all length characters as silence when passing them to the TTS. The TTS only sees what's in the papercup feature vector and nothing else. This causes two problems: 1) They are treated as silences, which they are not, silence does not coincide with any of those markers. 2) There is no distinction between any of the markers, all of them look the exact same when they are passed to the TTS. The second problem cannot be fixed without adding new dimensions or values for existing dimensions to the feature vector, which breaks all compatibility to previous models.

I will make a branch with support for tone and length characters in the phoneme string. It will not be in the main branch however, because it breaks compatibility with the pretrained model. Once there is a pretrained model available that knows tone and length markers, it will become the main branch. Making this branch will take some time, the semester is about to start, so I have to spend 100% of my time on teaching right now.

I'll close this PR and recommend that you either wait for the "official" implementation if it's not urgent, or you continue experimenting in your fork.

**Comment by michael-conrad** [comment]
OK, thanks for the explanations.

I was thinking when looking at the code and saw that the language id is a single tensor, I did not realize it was getting mapped into inputs based on tensor value.

**Pull request closed without merging**
